#!/usr/bin/env bash
#configures a new ubuntu machine
#creates a customized http header

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
sudo touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

print %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Serverd-By $HOSTNAME;
	root /var/www/html;
	index index.html index.htm
	location /redirect_me {
		return 301 https://www.youtube.com
	}
	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal
	}
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
