#!/usr/bin/python3
#customization of 404-error_page

#updating packages and installing nginx
sudo apt-get update
sudo apt-get install -y nginx

#creating a html index page
echo "Hello World!" | sudo tee /var/www/html/index.html

#performing a "move permanently redirection (301)"
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#creating a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

#creating a custom http response
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#testing the configuration for syntax error
sudo nginx -t

#restart nginx
sudo service nginx restart