#!/usr/bin/env bash
#install loadbalancer

sudo apt-get install --no-install-recomends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/original.cfg

echo "
frontend front
	bind *:80
	default_backend back
backend back
	balance roundrobin
	server 103576-web-01 18.206.206.12:80 check
	server 103576-web-02 100.26.211.123:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
