#!/usr/bin/env bash
#installs nginx and configures it to listen to port 80
#if succes prints "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
