#!/usr/bin/env bash
#configures ufw firewall to block all incoming traffic except tcp 22 433 80

sudo ufw reset
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 433/tcp
sudo ufw allow 80/tcp
sudo ufw enable
